name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain the motivation or use case.
